CMAKE_OSX_DEPLOYMENT_TARGET=10.10
#CMAKE_XCODE_ATTRIBUTE_GCC_VERSION="com.apple.compilers.llvmgcc52"
CMAKE_XCODE_ATTRIBUTE_GCC_VERSION=""

MATLAB_INCLUDE_DIR="/Applications/MATLAB_R2015a.app/extern/include/"
MATLAB_LIB_DIR="/Applications/MATLAB_R2015a.app/bin/maci64/"

cmake ../ \
    -DCMAKE_OSX_DEPLOYMENT_TARGET=$CMAKE_OSX_DEPLOYMENT_TARGET \
    -DCMAKE_XCODE_ATTRIBUTE_GCC_VERSION=$CMAKE_XCODE_ATTRIBUTE_GCC_VERSION \
    -DMATLAB_INCLUDE_DIR=$MATLAB_INCLUDE_DIR \
    -DMATLAB_LIB_DIR=$MATLAB_LIB_DIR \
    -DCMAKE_BUILD_TYPE=Debug \
    -G Xcode $@
